### ISSUE TITLE
SfImageEditor doesnot show capture image from camera xamarin.forms

### ISSUE THREAD

**Issue by softsan** [syncfusion/xamarin-demos#1]
SfImageEditor does not show capture image from camera in xamarin.forms. I've filed a support case and here is the link for the same:

https://www.syncfusion.com/support/directtrac/incidents/215670

Also prepare sample and uploaded at following location:
https://drive.google.com/file/d/1vGprlONftc0uTVpyKkLwkxPDcTUFDrU9/view?usp=sharing

**Comment by michaelprabhu** [comment]
We have created a sample based on your code snippet to load image to the Image Editor from camera. 
 
The following things are missing in your attached sample and we have modified the same in the sample
 
1)Need to set Binding context to the page
 
2)Horizontal and Vertical options has been set to the Image Editor if it is inside a stacklayout
 
 <imageeditor:SfImageEditor HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand" Source="{Binding Image}" />
 
Please find the sample from the below link,
 
Sample Link : http://www.syncfusion.com/downloads/support/directtrac/general/ze/ImageStream924039999.zip  
 
As of now have validated your query in iOS platform, we are validating the same in Android platform. Can you please let us know in which platform you are facing the mentioned issues, so it will be helpful for us to provide a better solution?
