### ISSUE TITLE
sfimageeditor not support mvvm I

### ISSUE THREAD

**Issue by aseif** [syncfusion/xamarin-demos#2]
sfimageeditor not support mvvm as ImageSaving and ImageSaved events not bindable

**Comment by michaelprabhu** [comment]
We are unable to reproduce the issue, "**ImageSaving and ImageSaved event not bindable**" in image editor. Please  find the sample from below location.
Sample Link: http://www.syncfusion.com/downloads/support/directtrac/general/ze/EventBinding2138321466.zip 

We request you to try our sample , if you are still facing problem please modify the  above sample and send it back to us . This will be helpful for us to provide you a good solution

**Comment by aseif** [comment]
thanks,  it works fine
