### ISSUE TITLE
CloseButton of SfChip not working with latest version of Syncfusion & Xamarin prerelease

### ISSUE THREAD

**Issue by SunshineSpring666** [syncfusion/xamarin-demos#20]
The CloseButton of Chip does not work anymore after updating packages to latest version. Please check if any compatibility issue or bug exists. Thanks a lot.

**Comment by HemalathaMarikuma-syncfusion** [comment]
Hi @SunshineSpring666,

We would like to let you know that the reported issue is a known issue and we have fixed the same and that is included in our latest v18.1.0.52 version. Could you please ensure the same and let us know.

Regards,
Hemalatha M.

**Comment by SunshineSpring666** [comment]
Checked. The bug is fixed. 
Thanks.

Regards,
Sunshine
