### ISSUE TITLE
Converting Doc to Pdf causes non-ASCII numeral/symbols to overlap with characters in the same paragraph

### ISSUE THREAD

**Issue by SunshineSpring666** [syncfusion/xamarin-demos#23]
Syncfusion documentation provides detailed steps to generate doc in code and convert it to pdf using DocIORenderer. 
    **It works perfectly when the doc contains only ASCII characters. However, when character-based language (e.g., Chinese, Japanese, etc.) is in the paragraph, the numbers (0~9) and symbols (e.g., _  /  ~, etc)  overlap with other characters in the same paragraph in the converted PDF.**
    The doc file looks perfect. The bug happens when converting it to PDF.

Simple demo to reproduce the bug:
1.  Init a doc instance.  WordDocument doc = new WordDocument();
2.  Add a section.  WSection sec = doc.AddSection() as WSection;
3.  Create a paragraph.  IWParagraph p = sec.HeadersFooters.Header.AddParagraph();
4.  **Add the paragraph with some character-based language content and numerals/symbols.   p = sec.AddParagraph(); p.AppendText("现在是第5天，日期2020年5月16日");**
5.  Save doc to memory stream.   MemoryStream stream = new MemoryStream();
                                                      doc.Save(stream, FormatType.Docx);
6.  Convert doc to PDF.   DocIORenderer render = new DocIORenderer();
                                        PdfDocument pdf = render.ConvertToPDF(doc);
                                        render.Dispose();
                                        doc.Dispose();
                                        MemoryStream pdfStream = new MemoryStream();
                                        pdf.Save(pdfStream);
                                        pdf.Close();
                                        DependencyService.Get<IPrint>().PrintStream(pdfStream, "Character-based_PDF_Convertion.pdf");

The overlapped output pdf snip image is as follows:
![Annotation 2020-05-16 220112](https://user-images.githubusercontent.com/42401603/82121667-622fbf00-97c1-11ea-9f26-f6d0b455d0f6.png)

**Comment by ManishSync** [comment]
Hi @SunshineSpring666 ,

We have tried to reproduce the reported issue at our end but its working fine without any issue. On further checking, we have found that the reported issue occurs due to the missing of font (Arial Unicode MS) in your system. So, we suggest you to install the necessary fonts in your system and then perform PDF conversion in your end. 

If you face difficulties installing the missing fonts, then, please use our font substitution feature which as mentioned in our UG documentation page.

Please find the PDF document generated at our end.
https://www.syncfusion.com/downloads/support/directtrac/general/pd/ResultNew95298366

Please refer the following link for font substitution.
https://help.syncfusion.com/file-formats/docio/word-to-pdf#font-substitution

Regards,
Manikandan Ravichandran

**Comment by SunshineSpring666** [comment]
Thanks! 
It works after installing the specified font on Windows. 
However, on Android, devices need to be rooted before installing ttf font. I'll try the font substitution workaround later.

Best regards,
Sunshine

**Comment by SunshineSpring666** [comment]
I run Font Substitution on Android with the following code snippet. It turns out that the args.OriginalFontName is always "Times New Roman" each time the hooked event get called, leading to a output pdf with overlapped characters due to improper Font. 
    Do I missing something? Or should I set Font explicitly via some method and then the Font will be correct?  Thanks a lot.

 ```
        void FontSettings_SubstituteFont(object sender, SubstituteFontEventArgs args)
        {
            if (args.OriginalFontName == "Arial Unicode MS")
                args.AlternateFontName = "Arial";
            else
                args.AlternateFontName = "Times New Roman";
        }

        private void PrintTestButton_Clicked(object sender, EventArgs e)
        {
            WordDocument doc = new WordDocument();
            WSection sec = doc.AddSection() as WSection;
            IWParagraph p = sec.AddParagraph(); p.AppendText("现在是第5天，日期2020年5月16日");

            doc.FontSettings.SubstituteFont += FontSettings_SubstituteFont;
            DocIORenderer render = new DocIORenderer();
            PdfDocument pdf = render.ConvertToPDF(doc);
            doc.FontSettings.SubstituteFont -= FontSettings_SubstituteFont;
            render.Dispose();
            doc.Dispose();
            MemoryStream pdfStream = new MemoryStream();
            pdf.Save(pdfStream);
            pdf.Close();
            DependencyService.Get<IPrint>().PrintStream(pdfStream, "Test.pdf");
        }
```

**Comment by SunshineSpring666** [comment]
**[Issue Appear Again] With latest Syncfuion DocIO and Xamarin 5**, installing "Arial Unicode MS" font or use Font Substitute doesn't solve the overlapping issue again. I guess it might be caused by the internal modification of font file invoking mechanism in Xamarin 5.0.0? Thanks a lot.

**Comment by SunshineSpring666** [comment]
Hi Manikandan,
Even adding "ArialUnicodeMS.ttf" as an Embedded Resource in Shared Project (as instructed in [Syncfusion documentation)](https://help.syncfusion.com/file-formats/docio/word-to-pdf#font-substitution) doesn't work anymore. Pretty weird.

` args.AlternateFontName = (args.OriginalFontName == "Arial Unicode MS") ? "Arial" : "Times New Roman";`
or
`args.AlternateFontStream = typeof(App).GetTypeInfo().Assembly.GetManifestResourceStream("Factory.ArialUnicodeMS.ttf");`

Issue exist on UWP/Android/iOS with:
Xamarin.Forms  5.0.0
Syncfusion.Xamarin.DocIO   18.3.0.44.
Arial Unicode MS.ttf   1.0
Visual Studio 2019   16.7.7

Many thanks.
