### ISSUE TITLE
Button's click event in the DropDownFooter of SfAutoComplete not get called

### ISSUE THREAD

**Issue by SunshineSpring666** [syncfusion/xamarin-demos#24]
As the documentation suggests, the footer could be designed to respond to the user's "Add New" action. (https://help.syncfusion.com/xamarin/autocomplete/header-and-footer)

However, if we put a Button in the footer, the Click event of the button don't get called when the footer is tapped. Are there any further configurations needed to be set to get it work? Many thanks.

**Comment by RabhiaBehamK** [comment]
Hi Team,

Greetings from Syncfusion.

We have prepared a sample with SfComboBox with the Button in the DropDownFooterView. And the click event is invoked as expected. Please have the sample with which we have ensured,

**Sample:** https://www.syncfusion.com/downloads/support/directtrac/general/ze/FooterView1423348227.zip

Please check with the above sample and if the requirement differs please modify the above solution with the reproducing steps which will be helpful for us to provide the solution at the earliest.

**Comment by SunshineSpring666** [comment]
Thanks. The solution of using SfComboBox instead of SfAutoComplete is a proper workaround in such cases.
