### ISSUE TITLE
[Bug] SfListView have compatibility issue with Xamarin.Forms 4.7.0.937pre4 and above (4.7.0.968 the Stable Release) on UWP

### ISSUE THREAD

**Issue by SunshineSpring666** [syncfusion/xamarin-demos#25]
Starting from Xamarin.Forms 4.7.0.937-pre4 and **Stable Release(4.7.0.968)** , the latest version of SfListView behaves abnormally on **UWP**:

The **tap event** of an item in SfListView get called in **mislocation** or never get called (caused by malposition). For example, when the 8th row is tapped actually, the 2nd row or a button in the UI get called its own tapped event. Weird.

Since the issue still exists when compiled with Xamarin.Forms 4.7.0 Stable Release, this feedback is provided to help figure out the cause. 
Thanks a lot. Have a good day.

**Comment by LakshmiNatarajan21** [comment]
The Xamarin.Forms ScrollView is broken in the latest version of Xamarin.Forms 4.7.0.968. ScrollView is used inside SfListView that caused a break in the SfListView.

Kindly follow up with Xamarin.Forms bug report regarding the same,
**Bug report**: https://github.com/xamarin/Xamarin.Forms/issues/11106

Regards,
Lakshmi Natarajan

**Comment by SunshineSpring666** [comment]
Got it. Thanks!
