### ISSUE TITLE
why my SfBadgeView like this?

### ISSUE THREAD

**Issue by bobotan** [syncfusion/xamarin-demos#26]
![image](https://user-images.githubusercontent.com/12933249/85486871-13661800-b5fe-11ea-9ecd-866ca86f8d1b.png)

**Comment by bobotan** [comment]
i can't understand

**Comment by bobotan** [comment]
![image](https://user-images.githubusercontent.com/12933249/85487751-c2efba00-b5ff-11ea-8747-7217c1813712.png)

**Comment by jeyakasipandi** [comment]
<badge:SfBadgeView HorizontalOptions="Center"   VerticalOptions="Center" BadgeText="New">             <badge:SfBadgeView.BadgeSettings>                 <badge:BadgeSetting                   BadgePosition="TopRight">                 </badge:BadgeSetting>             </badge:SfBadgeView.BadgeSettings>             <badge:SfBadgeView.Content>                 <Grid>                     <Button WidthRequest="80" HeightRequest="50"   Text="Primary" BackgroundColor="Gray">                     </Button>                 </Grid>           </badge:SfBadgeView.Content>         </badge:SfBadgeView>
--

**Comment by bobotan** [comment]
Thank you very much！it works
