### ISSUE TITLE
Missing Init Code in samples

### ISSUE THREAD

**Issue by seank-com** [syncfusion/xamarin-demos#3]
All the samples make a call to an init function that as near as I can tell is not provided in source code form.

On Android, the implementation of every ```MainActivity::OnCreate``` has the following line:

```
SampleBrowser.Core.Droid.CoreSampleBrowser.Init(Resources, null);
```

On iOS, the implementation of every ```AppDelegate::FinishedLaunching``` has the following line:

```
SampleBrowser.Core.iOS.CoreSampleBrowser.Init(UIScreen.MainScreen.Bounds, app.StatusBarFrame.Size.Height);
```

As near as I can figure this code lives in the ```SampleBrowser.Core.16.3.0.21.nupkg``` nuget package and is where the magic sauce is that keeps the controls from being rendered under the notification area up at the top on iOS and who know what other magic. I assume we should not ship the SampleBrowser.Core package as part of our syncFusion apps, so is there any other way we can see what is happening in this init function?

**Comment by michaelprabhu** [comment]
Hi,
“SampleBrowser.Core” package is not needed, even when using our components in your applications. The particular package is internally needed for our sample browser, where we have showcased all our components and its features. In the Init method, we have gotten the application size and status bar height, based on that we have internally calculated the screen height by excluding the status bar height and navigation bar height. Moreover, these calculations are needed for our sample browser only. You can use our controls without the SampleBrowser.Core package.

**Comment by seank-com** [comment]
I was more interested in how you "calculated the screen height by excluding the status bar height and navigation bar height" so I could do that in my application also, I've searched all over the internet and this is a black art to get Xamarin Forms to work well cross platform. Many recommend abandoning Xamarin Forms altogether in favor of a native view for iOS and a native view for Android. I've learned a ton about writing a good performant Xamarin Forms application using your sample and was hoping to figure this part out as well.

**Comment by seank-com** [comment]
Here is a picture to demonstrate the issue I am having

![image](https://user-images.githubusercontent.com/1326518/47860483-dfe1d480-ddad-11e8-85e4-07c747830b24.png)

**Comment by IoTFier** [comment]
I am in the same boat as @seank-com.

Sharing the code of SampleBrowser.Core will be a great help to the Syncfusion users and community of Xamarin developers.

@michaelprabhu,  Is that possible ? Can you open up that repo to us ?

Thanks

**Comment by IoTFier** [comment]
@michaelprabhu, while debugging the app it is not as clear on how views are loaded inside the application.
Looks like the main navigation page is of type contentPage hosting a grid with two rows. Top row having a label and and setting icon ; and bottom row hosting a SfTabView with each tab having its own instance of SfSchedule. 

Can you please share the code of main hosting page of the App?

Thanks

**Comment by RajasekarBabu** [comment]
We will consider to ship SampleBrowser.Core source project in our upcoming builds. I am closing this issue now.

**Comment by seank-com** [comment]
This is great news, I've basically shelved my SyncFusion project until I can figure this out.

**Comment by dharamhbtik** [comment]
is SampleBrowser.Core is available in current build? I can't locate it/
