### ISSUE TITLE
[Bug] SfSchedule raises UnhandledExceptionEventArgs Exception when double tapping the appointment if SyncfusionThemeDictionary is specified on UWP

### ISSUE THREAD

**Issue by SunshineSpring666** [syncfusion/xamarin-demos#31]
On UWP, when specifying SyncfusionThemeDictionary as instructed in the documentation, SfSchedule raises weird Excepion when tapping an Appointment:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Syncfusion.SfSchedule.UWP.AppointmentControl.ClearSelection()
   at Syncfusion.SfSchedule.UWP.SelectionController.ClearAppointmentSelection()
   at Syncfusion.SfSchedule.UWP.SelectionController.UpdateAppointmentSelection(AppointmentControl appointmentControl, ScheduleAppointment appointment, DateTime dateTime)
   at Syncfusion.SfSchedule.UWP.SelectionController.OnAppointmentMouseLeftButtonDown(AppointmentControl ...

Environment:
Visual Studio 2019 16.7.5
Xamarin.Forms 4.8
Windows 10  20231

**Here is a simple demo to show the bug:** Thanks.
---------------TestPage.xaml-------------------
`<?xml version="1.0" encoding="utf-8" ?>
<ContentPage x:Class="Demo.Views.TestPage"
             xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:sd="clr-namespace:Syncfusion.SfSchedule.XForms;assembly=Syncfusion.SfSchedule.XForms" 
             xmlns:syncTheme="clr-namespace:Syncfusion.XForms.Themes;assembly=Syncfusion.Core.XForms"
             x:Name="this"
             BindingContext="{x:Reference this}">

    <ContentPage.Resources>
        <syncTheme:SyncfusionThemeDictionary>
            <syncTheme:SyncfusionThemeDictionary.MergedDictionaries>
                <syncTheme:DarkTheme />
            </syncTheme:SyncfusionThemeDictionary.MergedDictionaries>
        </syncTheme:SyncfusionThemeDictionary>
    </ContentPage.Resources>

    <sd:SfSchedule DataSource="{Binding Appointments}" ScheduleView="WeekView"/>
    
</ContentPage>`

------------------TestPage.xaml.cs------------------
`using Syncfusion.SfSchedule.XForms;
using System;
using Xamarin.Forms;

namespace Demo.Views
{
    public partial class TestPage : ContentPage
    {
        public TestPage()
        {
            InitializeComponent();
        }

        public ScheduleAppointmentCollection Appointments { get; set; } = new ScheduleAppointmentCollection();

        protected override void OnAppearing()
        {
            base.OnAppearing();
            Appointments.Add(new ScheduleAppointment()
            {
                StartTime = DateTime.Now,
                EndTime = DateTime.Now.AddHours(6),
                Subject = "Meeting",
                Location = "Hutchison road",
            });
        }     
    }
}`

**Comment by Muniappan612** [comment]
Hi @SunshineSpring666  
 
We are glad to let you know that we have fixed the reported issue “Exception when double-tapping the appointment if SyncfusionThemeDictionary is specified on UWP” and included the fix in our 2020 Volume 3 SP release update version v18.3.0.47 and is available for download under the following link. 
 
https://www.syncfusion.com/forums/159441/essential-studio-2020-volume-3-service-pack-release-v18-3-0-47-is-available-for-download

 We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance. 
 
Regards, 
SaiGanesh Sakthivel

**Comment by SunshineSpring666** [comment]
Thanks a lot.

Regards,
SunshineSpring666
