### ISSUE TITLE
[Bug] Doc to PDF conversion Character Overlap on Android (Font Substitution not working)

### ISSUE THREAD

**Issue by SunshineSpring666** [syncfusion/xamarin-demos#33]
When converting doc to pdf, if the document **contains character-based content and numeral/symbols**, the font substitution does not working as expected, causing overlapping in pdf file.

On UWP, FontName of CharacterFormat can be specified to use a pre-installed **Microsoft YaHei** or **Arial Unicode MS** as a workaround. However, Font Substitution doesn't work.
On Android, either specifying FontName to **Droid Sans Fallback** or using Font Substitution doesn't work.
![CharNumeralOverlap](https://user-images.githubusercontent.com/42401603/101599136-3792a580-3a34-11eb-970d-07994b9fd5fa.png)

Thanks a lot.

Environment:
Windows 10 Build 20246
Visual Studio 2019 16.8.3
Xamarin 5.0.0
Syncfusion 18.3.0.53
Android 10

Code Snippet to reproduce the issue:

void OnButtonClicked(object sender, EventArgs args)
{
            WordDocument document = new WordDocument();
            WSection section = document.AddSection() as WSection;
            IWParagraph paragraph = section.AddParagraph();
            WTextRange textRange = paragraph.AppendText("第5天，日期2020年12月9日") as WTextRange;
            //textRange.CharacterFormat.FontName = "Microsoft YaHei"; //"Arial Unicode MS";  // Specifying FontName WORKS on UWP
            document.FontSettings.SubstituteFont += FontSettings_SubstituteFont;            // Font Substitution NOT WORK
            DocIORenderer render = new DocIORenderer();
            PdfDocument pdfDocument = render.ConvertToPDF(document);
            document.FontSettings.SubstituteFont -= FontSettings_SubstituteFont;
            render.Dispose();
            document.Dispose();
            MemoryStream outputStream = new MemoryStream();
            pdfDocument.Save(outputStream);
            pdfDocument.Close();
            Xamarin.Forms.DependencyService.Get<ISave>().SaveAndView("CharOverlapWithNumerals.pdf", "application/pdf", outputStream);
}

void FontSettings_SubstituteFont(object sender, SubstituteFontEventArgs args)
        {
            if (args.OriginalFontName == "Arial Unicode MS")
                args.AlternateFontName = "Droid Sans Fallback";  //"Microsoft YaHei";
            else
                args.AlternateFontName = "Times New Roman";
        }

**Comment by SunshineSpring666** [comment]
For Android 10, specifying FontName to "Noto Serif CJK“ or “Noto Serif CJK SC” doesn't solve the overlapping issue either.

**Comment by MohanaselvamJ** [comment]
Hi @SunshineSpring666 ,

To preserve the Chinese character properly, we suggest you to use the below solution:

**For UWP:**
Use FontName = “Arial Unicode MS”, as per you mentioned earlier.
**For Android:**
We suspect Arial Unicode MS font is not available in that environment and it may rise preservation problem in resultant PDF. To resolve this, we recommend you to set corresponding font as alternate font stream using [SubstituteFont](https://help.syncfusion.com/cr/file-formats/Syncfusion.DocIO.DLS.FontSettings.html) event.

**Code snippet:**

WordDocument document = new WordDocument();
WSection section = document.AddSection() as WSection;
IWParagraph paragraph = section.AddParagraph();
WTextRange textRange = paragraph.AppendText("第5天，日期2020年12月9日") as WTextRange;
//Set font which preserve chinese characters properly
textRange.CharacterFormat.FontName = "Arial Unicode MS";
document.FontSettings.SubstituteFont += FontSettings_SubstituteFont;
DocIORenderer render = new DocIORenderer();
PdfDocument pdfDocument = render.ConvertToPDF(document);
document.FontSettings.SubstituteFont -= FontSettings_SubstituteFont;
render.Dispose();
document.Dispose();
MemoryStream outputStream = new MemoryStream();
pdfDocument.Save(outputStream);
pdfDocument.Close();


void FontSettings_SubstituteFont(object sender, SubstituteFontEventArgs args)
{
    //Sets the alternate font when a specified font is not installed in the production environment
    if (args.OriginalFontName == "Arial Unicode MS")
    {
       Assembly assembly = typeof(App).GetTypeInfo().Assembly;
       //Read font file
       Stream templateStream = assembly.GetManifestResourceStream("Sample.Assets.ARIALUNI.TTF");
       args.AlternateFontStream = templateStream;
    }
}


Refer:
https://help.syncfusion.com/file-formats/docio/word-to-pdf?cs-save-lang=1&cs-lang=asp.net%20core#event-handler-to-use-alternate-font-without-installing 

Thanks,
Mohanaselvam

**Comment by SunshineSpring666** [comment]
Sorry for belated reply. 
It worked with latest Xamarin(5.0.0.1829-pre6) and Syncfusion(18.4.0.31). The overlapping issue is resolved. 

Thanks a lot. Merry Christmas and Happy New Year to you guys on Syncfusion team!
