### ISSUE TITLE
SfExpander raise Exception and not Rendered normally

### ISSUE THREAD

**Issue by SunshineSpring666** [syncfusion/xamarin-demos#36]
Hi Syncfusion Team,
    On UWP and Android, SfExpander doesn't get rendered and raises InvalidOperationException: "Collection was modified; enumeration operation may not execute."
    The SfExpander demo in official Syncfusion Components for Xamarin.Forms (UWP App) doesn't get rendered correctly either.

![SfExpanderScreenshot1](https://user-images.githubusercontent.com/42401603/108671052-e5cdc780-751a-11eb-9a50-aee893b4a19c.png)
![SfExpanderScreenshot2](https://user-images.githubusercontent.com/42401603/108671059-e9614e80-751a-11eb-9042-345c4ab20c72.png)

Environment:
Visual Studio 2019 ver. 16.8.5
Windows 10 ver. 21292 (SDK ver. 19041) / Android 10 (API ver. 29)

Thanks a lot and have a nice day.
Regards

**Comment by LakshmiNatarajan21** [comment]
Hi @SunshineSpring666 ,

Greetings from Syncfusion.

We have checked the reported query “SfExpander raise Exception and not Rendered normally” from our side. We would like to inform you that we are unable to reproduce the reported scenario at our side.

**Additional information:**
**VS configuration:** Microsoft Visual Studio Professional 2019 - Version 16.7.6
**Android** – Realme X2 Pro  Android 10 - API 29
**UWP** – Windows 10, version 2004 (10.0; Build 19041)
**Xamarin.Forms:** 4.5.0.617
**Xamarin:** 16.7.000.456
**Xamarin Designer:** 16.7.0.495
**Xamarin Templates:** 16.7.85

Please share the following details to check further from our side which would be helpful for us to check on it and provide you the solution as soon as possible.

- Share Syncfusion and Xamarin.Forms version
- Share device configuration details

Regards,
Lakshmi Natarajan

**Comment by SunshineSpring666** [comment]
Hi Lakshmi,
I tried to set up a demo to make it reappear but everything works fine if I put the exact same related code into demo project. Weird. However, when I tested it in a separate page inside my project, the problem appeared (only on UWP). **Since the environments are the same, I guess some configuration/modules in the project may bother the rendering process.** 

- Syncfusion 18.4.0.43, Xamarin 5.0.0.2012
- VS Community 2019 16.8.5

**I'll try to figure it out. If it relates to the expander control, I'll post detailed feedback.**
Syncfusion.Xamarin is by far the best control sets ever. Thanks for you guys.

Regards,
SunshineSpring

**Comment by SunshineSpring666** [comment]
Update: 
    I did further debugging and realize the Expander actually got rendered. But because I put several expander in a vertical Scrollview, the Expander content didn't get stretched to its needed size automatically (the situation only exist on UWP). 
    I got a workaround by specifying a fixed HeightRequest for each expander and make the content scroll in horizontal direction.
    Thanks for your help.
    Best Regards,
    SunshineSpring
