### ISSUE TITLE
Setting  icon on the top row

### ISSUE THREAD

**Issue by IoTFier** [syncfusion/xamarin-demos#4]
Hi, I would like to reuse the code behind RecursiveAppointments.xaml and its view model.

Is that ok to use it in my App? Just wanted to be sure of the license on usage of this code.

I also see that SampleBrowser.SfSchedule.props file has a itemgroup that refers to RecurrenceAppointments.xaml / .cs and its  , View Model.
Is there a documentation that explains the intent to use this view in this manner via MSBuild steps / props file?

Thanks

**Comment by IoTFier** [comment]
Hi Syncfusion team, @vijays-git , @Velusamys 
Can someone please respond with your helpful input ?

Thanks,

**Comment by IoTFier** [comment]
@RajasekarBabu , can you share with the code of SampleBrowser.Core?
Upon debugging it was clear which page is initiated in the App.cs file ?
May be we could learn more / best practices from your SampleBrowwser .Core code.

Please share that code.

**Comment by RajasekarBabu** [comment]
We will consider to ship SampleBrowser.Core source project in our upcoming builds. I am closing this issue now.
