### ISSUE TITLE
the demos do not build, even with releases patchs it still does not build

### ISSUE THREAD

**Issue by mach37** [syncfusion/xamarin-demos#5]
Both sample downloads from installer and the downloads from github are both out of date.
![image](https://user-images.githubusercontent.com/12221440/49487666-7ec87900-f811-11e8-8060-d7c733cfe80b.png)
________________
![image](https://user-images.githubusercontent.com/12221440/49488016-f34fe780-f812-11e8-9c43-584e76420648.png)

**Comment by ArunSivaR** [comment]
Hi @mach37 ,

Thanks for contacting Syncfusion support,

We have checked this issue “Demo samples doesn’t build” and it works fine from our side, and we suspect that you didn’t clear the nuget cache, which may cause this error, please clear nuget cache by referring the following link:

Link: https://www.syncfusion.com/kb/6987/how-to-clear-nuget-cache

We hope that this will helps you, kindly revert us if you have any concern.

Regards,
Arun Siva R

**Comment by mach37** [comment]
That did not resolve the building of the app, can you please tell me what else I need to do.

**Comment by ArunSivaR** [comment]
Hi @mach37 

Thanks for the update,

We have analyzed your query “Unable to build samplebrowser” and it works fine from our side, we have attached the sample which we have checked, please find the sample below.

Sample: [ScheduleSampleBrowser](http://www.syncfusion.com/downloads/support/directtrac/general/ze/Schedule-1990986764)

Kindly revert us if you have any concern.

Regards,
Arun Siva R

**Comment by waltergrimmvie** [comment]
Don't worry about samples not compiling, I do all stuff, check all nuget, clear cache etcetc, but they simply do not compile, I assume the samples where made with some old version and the new vs is having issues, so it works on their dev PC, but I am having this in 8 from 10 cases

**Comment by mach37** [comment]
Hello @waltergrimmvie @ArunSivaR I tried it again today, they still dont build with latest current targets (.NET)

Also the nugets are old

**Comment by ArunSivaR** [comment]
Hi @mach37 

Thank you for the update.

We have analyzed the reported issue “The samplebrowser doesn’t build with new nugets” and it works fine from end, we have attached the samplebrowser with latest nuget version, and the sample is following by.

Sample: [ScheduleSampleBrowser](http://www.syncfusion.com/downloads/support/directtrac/general/ze/Schedule1126729138)

If the issue remains same with this sample, kindly revert us back with more details like the VS version, Windows version and the build environment details, which help us to analyze and resolve the reported issue.

Regards,
Arun Siva R

**Comment by mach37** [comment]
Hello, I still have this issue. I am using VS 2017 and VS 2019 (RC), both have this issue, Win 10
.net 4.72 and also .Net Core latest

![image](https://user-images.githubusercontent.com/12221440/55688545-b4a87600-5947-11e9-82ed-9b237e9c3255.png)

**Comment by RajasekarBabu** [comment]
@mach37 Can you try with our latest samples? We have upgraded our samples project recently. I am closing this issue now.
