### ISSUE TITLE
Chinese characters are not displayed

### ISSUE THREAD

**Issue by bobotan** [syncfusion/xamarin-demos#53]
PdfDocument doc = new PdfDocument();
            doc.PageSettings.Orientation = PdfPageOrientation.Landscape;
            doc.PageSettings.Size = PdfPageSize.A4;
            //Add a page.

            PdfPage page = doc.Pages.Add();

            //Create a PdfGrid.
            PdfGrid pdfGrid = new PdfGrid();
            //Create a DataTable.
            DataTable dataTable = new DataTable();

            //Add columns to the DataTable
            dataTable.Columns.Add("名字");
            dataTable.Columns.Add("Name");
            dataTable.Columns.Add("Salary");

            //Add rows to the DataTable.
            dataTable.Rows.Add(new object[] { "中文字符", "Clay", "$10,000" });
            dataTable.Rows.Add(new object[] { "E02", "Thomas", "$10,500" });
            dataTable.Rows.Add(new object[] { "E03", "Simon", "$12,000" });

            //Assign data source.
            pdfGrid.DataSource = dataTable;

            for (int i = 0; i < pdfGrid.Columns.Count; i++)
            {
                for (int j = 0; j < pdfGrid.Rows.Count; j++)
                {
                    pdfGrid.Columns[i].Width = 100;
                    pdfGrid.Rows[j].Height = 50;
                   
                }
            }

            PdfGridBuiltinStyleSettings tableStyleOption = new PdfGridBuiltinStyleSettings();
            tableStyleOption.ApplyStyleForBandedRows = true;
            tableStyleOption.ApplyStyleForHeaderRow = true;

            //Apply built-in table style
            pdfGrid.ApplyBuiltinStyle(PdfGridBuiltinStyle.GridTable4Accent4, tableStyleOption);
            //Draw the PdfLightTable.
            pdfGrid.Draw(page, Syncfusion.Drawing.PointF.Empty);

            //Save the PDF document into stream

            MemoryStream stream = new MemoryStream();

            doc.Save(stream);

            //Close the document.

            doc.Close(true);

when test my code  Chinese characters are not displayed!
![image](https://user-images.githubusercontent.com/12933249/182817213-753f0ca5-aa12-4156-ae71-c55fc003f2bc.png)

**Comment by GowthamrajKumar25** [comment]
Hi bobotan,

We can draw the text of a Chinese character using the supported font file from the local file system by providing the path of the TrueType font location. We need to refer the suitable font file to the Assert folder. Please refer the step 7 of the below KB documentation for adding the font file to the Assert folder and set the Build Action to Embedded Resource,
KB: https://www.syncfusion.com/kb/9691/how-to-draw-unicode-characters-in-a-pdf-in-xamarin
KB: https://www.syncfusion.com/kb/9740/how-to-draw-unicode-text-in-pdf-tables

Please refer to the below code snippet for adding a Chinese character in a PdfGrid cell,

```
//Get the font file as stream.
Stream fontStream = typeof(MainPage).GetTypeInfo().Assembly.GetManifestResourceStream("UnicodeText.Assets.arial-unicode-ms.ttf");

//Create a new PdfTrueTypeFont instance.
PdfTrueTypeFont font = new PdfTrueTypeFont(fontStream, 14);

//Assign font to PdfGrid.
pdfGrid.Style.Font = font;

```

We have attached the sample and output document for your reference, please find the sample from below,
Sample: https://www.syncfusion.com/downloads/support/directtrac/general/ze/UnicodeText-10220074
Output: https://www.syncfusion.com/downloads/support/directtrac/general/pd/OutputGrid-1511277718

Please try the above sample on your end and let us know if you need any further assistance in this.

Regards,
Gowthamraj K
