### ISSUE TITLE
Code files

### ISSUE THREAD

**Issue by Noredless** [syncfusion/xamarin-demos#8]
Hi,

Where upload this code files? And which use file types?

**Comment by bharathirajauk** [comment]
Hi Noredless,

We are not clear with your query. However, we suspect that you are asking Syncfusion Xamarin sample code. It is available in the below location.

Xamarin demo samples: https://github.com/syncfusion/xamarin-demos/tree/master/Forms 

If the above details are not related to your query, then please share more details regarding your query. We will check and update response.

Regards,
Bharathi.
