### ISSUE TITLE
Pull to refresh on SFListview

### ISSUE THREAD

**Issue by whitewabbit** [syncfusion/xamarin-demos#9]
When sflistview is empty, pull to refresh does not work.

**Comment by DineshBabuYadav** [comment]
Hi John,

Sorry for the inconvenience caused.

Based on the given details, we have loaded the collection into the ItemsSource after pull to refresh action is performed. And, the items are loaded properly and pulling indicator is loaded as expected. Please find the tested sample and video link for your reference below,

Sample: http://www.syncfusion.com/downloads/support/directtrac/237516/ze/ListViewSample-90327703 

Video: http://www.syncfusion.com/downloads/support/directtrac/237516/ze/237516_Video-489063947 
 
Could you please check with the above sample?. Also, please ensure that whether you have initialized the PullToRefresh and SfListView renderer in each platform’s renderer project. Please refer the following UG documentation link.

SfListView: https://help.syncfusion.com/xamarin/sflistview/getting-started#launching-the-sflistview-on-each-platform 
SfPullToRefresh: https://help.syncfusion.com/xamarin/sfpulltorefresh/getting-started#launching-the-sfpulltorefresh-on-each-platform 

If you are still facing the issue, please share some additional details like XAML page where ListView and PullToRefresh is loaded and its related page like where the ItemsSource is loaded etc., and if possible please modify the above sample to replicate the issue and share the replication procedure which would highly help us to analyze the issue better and update you an appropriate solution.

Please let us know if you require further assistance.

Regards,
Dinesh Babu Yadav

**Comment by whitewabbit** [comment]
Sorry too.. I've fix my issue thou in iOs, the loading icon sometimes bug out(it appeared to be small loading or a box that rotate not circle).. And also I have 2 sfListview in 1 page, i can't trigger the pull to refresh on the 2nd list view in both android and iOs..
